### ISSUE TITLE
Setup backend structure

### ISSUE THREAD

**Issue by KhyPhay** [sarathorn11/SMS-AEU-Y4-Backend#5]
**TODO:**

- [ ] Create a design pattern (MVC)
- [ ] Migrate tables
- [ ] Connect to database
- [ ]  Initialize Sequelize
- [ ] Setup Routes
- [ ] Test the API with the route that create above
